FROM golang:1.21

WORKDIR /spbstu-2024-lgp-ci

ENV TEST_DIR=/spbstu-2024-lgp-ci
ENV TEST_DIR_UTILS=/spbstu-2024-lgp-ci/utils
ENV TEST_DIR_COMMON=/spbstu-2024-lgp-ci/common
ENV TEST_MAKEFILE=/spbstu-2024-lgp-ci/utils/common.mk

COPY common common
COPY utils utils



