version: "3"

env:
  DOCKER_CONTAINER_NAME: "andrianovartemii/lgp-ci-utils"
  DOCKER_CONTAINER_TAG: '{{ .DOCKER_CONTAINER_TAG | default "latest" }}'
  DOCKER_FILE_PATH: "Dockerfile"
  DOCKER_PLATFORM: "linux/amd64"

  DOCKER_WORKDIR: "/home/student"
  DOCKER_COMMON_DIR: "{{ .DOCKER_WORKDIR}}/.ci_common"
  DOCKER_UTILS_DIR: "{{ .DOCKER_WORKDIR}}/.ci_utils"

  DOCKER_ARGS:
    - "--rm"
    - "-w {{ .DOCKER_WORKDIR }}"
    - "-v {{ .WORKDIR }}:{{ .DOCKER_WORKDIR }}:rw"
    - "-v {{ .COMMON_DIR}}:{{ .DOCKER_COMMON_DIR }}:ro"
    - "-v {{ .UTILS_DIR}}:{{ .DOCKER_UTILS_DIR }}:ro"
    - "-e WORKDIR={{ .DOCKER_WORKDIR }}"
    - "-e COMMON_DIR={{ .DOCKER_COMMON_DIR }}"
    - "-e UTILS_DIR={{ .DOCKER_UTILS_DIR }}"

tasks:
  build:
    - cmd: docker build --platform="{{ .DOCKER_PLATFORM }}" -t {{ .DOCKER_CONTAINER_NAME }} -f {{ .DOCKER_FILE_PATH }} .
  
  tag:
    deps: 
      - build
    cmds:
      - cmd: "docker tag {{ .DOCKER_CONTAINER_NAME }} {{ .DOCKER_CONTAINER_NAME }}:{{ .DOCKER_CONTAINER_TAG }}"
      - cmd: "docker tag {{ .DOCKER_CONTAINER_NAME }} {{ .DOCKER_CONTAINER_NAME }}:latest"

  push:  
    deps:
      - tag
    cmds: 
      - cmd: "docker push --disable-content-trust {{ .DOCKER_CONTAINER_NAME }}:{{ .DOCKER_CONTAINER_TAG }}"
      - cmd: "docker push --disable-content-trust {{ .DOCKER_CONTAINER_NAME }}:latest"
  
  bash:
    cmds:
      - cmd: docker run -it {{ .DOCKER_ARGS | join " " }} {{ .DOCKER_CONTAINER_NAME }}:{{ .DOCKER_CONTAINER_TAG }} bash {{ if .CLI_ARGS }} -c '{{ .CLI_ARGS_LIST | join " " }}' {{ end }}